@startuml
actor Пользователь
participant "Spring Security" as SS
participant "User Details Service" as UDS
database "users"
participant "AuthenticationManager" as AM
participant "AuthenticationProvider" as AP

Пользователь -> SS : Обращается к /login URL
SS -> UDS : Запрашивает UserDetails
UDS -> users: Запрашивает UserEntity по username
users -->>  UDS : Возвращает UserEntity
UDS -->>  SS : Возвращает UserDetails
SS ->AM: Передает UserDetails и password
AM ->AP: Передает UserDetails и password
AP ->AP: Проверяет данные
alt Данные корректны
    AP -->> AM : Результат аутентификации
    AM -->> SS : Результат аутентификации
    SS -> SS : Сохраняет информацию о пользователе в SecurityContextHolder
    SS -->> Пользователь : Перенаправление на домашнюю страницу
else Данные некорректны
    AP -->>  AM : Ошибка аутентификации
    AM -->>  SS : Ошибка аутентификации
    SS -->> Пользователь : Перенаправление на страницу логина с параметром error=true
end
@enduml
