@startuml

actor Пользователь
actor Преподаватель
actor Админ
actor Аноним
left to right direction
rectangle lessons {
    Аноним -up-> (Зарегистрироваться)
    Аноним -up-> (Войти)
    Аноним -up-> (Просматривать HomePage)

    Пользователь --> (CRUD для своих заявок)
    Пользователь --> (Просматривать HomePage)
    Пользователь --> (Выйти)

    Преподаватель -right->(Просматривать HomePage)
    Преподаватель -right-> (Выйти)
    Преподаватель -right->(CRUD для своих слотов)
    Преподаватель -->(Просматривать заявки по своим слотам)

    Админ -up-> (Просматривать HomePage)
    Админ -up-> (Выйти)
    Админ -up-> (CRUD для заявок)
    Админ -up-> (CRUD для слотов)
    Админ -up-> (Зарегистрировать нового Преподавателя)
}
(CRUD для своих заявок) --|> (CRUD для заявок)
(CRUD для своих слотов) --|>  (CRUD для слотов)
(Зарегистрировать нового Преподавателя)--|>(Зарегистрироваться)
(Просматривать заявки по своим слотам)  --|> (CRUD для заявок)

@enduml
